import
  unittest,
  assetfile # will be generated by the 'nimble test' task

suite "Nimassets Tests":
  test "Can Obtain Asset":
    check getAsset("tests/testassets/asset1.txt") == readFile("tests/testassets/asset1.txt")
